#cloud-config
# Эта штука называется cloud-init: позволяет инициализировать вирутальную машину при запуске (например, создать необходимые файлы)
# https://cloudinit.readthedocs.io/en/latest/
# https://yandex.cloud/en/docs/compute/concepts/vm-metadata

# Basic system setup
# hostname: example-host
# fqdn: example-host.example.com

# User setup configuration
ssh_pwauth: no
users:
  - name: ${DEFAULT_USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      # https://yandex.cloud/ru/docs/compute/operations/vm-connect/ssh#creating-ssh-keys
      - ${SSH_PUBLIC_KEY}

# Commands to run at the end of the cloud-init process
runcmd:
  - echo 'Hello, World!' > /etc/hello-world.txt
  # - systemctl restart nginx

write_files:
  - path: /etc/init.sql
    content: |
      CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';

  - path: /etc/nginx.default.conf
    content: |
      server {
          listen 80;
          # listen [::]:80 ipv6only=on default_server;
          
          server_name localhost;

          location / {
              proxy_pass http://${GW_LOCAL_HOST}:${GW_LOCAL_PORT}/;
              # proxy_set_header Host $host;
              # proxy_set_header X-Real-IP $remote_addr;
              # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              # proxy_set_header X-Forwarded-Proto $scheme;
          }

          location /nginx {
              return 200 'Hello World!';
          }
      }

  - path: /etc/fluentbit/fluentbit.conf
    content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     debug
          Daemon        off
          # Parsers_File  /fluent-bit/etc/parsers.conf

      # [FILTER]
      #     Name parser
      #     Match app.nginx
      #     Key_Name log
      #     Parser app_log_parser
      #     Reserve_Data On

      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              ${FLUENT_BIT_PORT}
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M

      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        ${YC_GROUP_ID}
          message_key     text
          level_key       severity
          default_level   WARN
          authorization   instance-service-account

  # - path: /etc/fluentbit/parsers.conf
  #   content: |
  #     [PARSER]
  #         Name   app_log_parser
  #         Format regex
  #         Regex  ^\[req_id=(?<req_id>[0-9a-fA-F\-]+)\] \[(?<severity>.*)\] (?<code>\d+) (?<text>.*)$
  #         Types  code:integer


# Final message, shown after cloud-init completes
# final_message: "The system is up, after $UPTIME seconds"
