services:
  postgres:
    container_name: asman-postgres-production
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    command: >
      postgres -c log_statement=all
    volumes:
      - ./configs/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asman-network

  redis:
    container_name: asman-redis-production
    image: redis:latest
    restart: always
    expose:
      - 6379
    networks:
      - asman-network

  # asman-mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: asman
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   networks:
  #     - asman-network

  # asman-mongo-express:
  #   image: mongo-express
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: asman
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://asman:password@asman-mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   ports:
  #     - 7870:8081
  #   networks:
  #     - asman-network

  asman-backend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: asman-backend-production
    restart: always
    environment:
      ENVIRONMENT: production

      POSTGRES_HOST: asman-postgres-production
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password

      USER_API_KEY: user-api-key
      ADMIN_API_KEY: master-api-key

      # FACEBOOK_CLIENT_ID: 1234
      # FACEBOOK_CLIENT_SECRET: facebook-client-secret
      # FACEBOOK_WEBHOOK_VERIFICATION_TOKEN: facebook-verification-token

      # Background
      BROKER_URL: redis://asman-redis-production
      RESULT_BACKEND: redis://asman-redis-production
      WORKER_SEND_TASK_EVENTS: 1

    depends_on:
      - redis
      - postgres

    ports:
      - 7860:3000
      - 5555:5555  # flower
    networks:
      - asman-network

networks:
  asman-network:

volumes:
  postgres_data:
