version: '3'

services:
  asman-postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - ./configs/postgres:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - asman-network

  # asman-mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: asman
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   networks:
  #     - asman-network

  # asman-mongo-express:
  #   image: mongo-express
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: asman
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://asman:password@asman-mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   ports:
  #     - 7870:8081
  #   networks:
  #     - asman-network

  asman-gateway:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: asman-gateway
    restart: always
    environment:
      POSTGRES_HOST: asman-postgres
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      MASTER_API_KEY: master-api-key
    ports:
      - 7860:3000
    networks:
      - asman-network

networks:
  asman-network:
