# Тестовое окружение то же, что и в core

services:
  # postgres для тестов
  asman-postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    command: >
      postgres -c log_statement=all
    volumes:
      - ./configs/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  # dynamodb для тестов
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    environment:
      DYNAMODB_LOCAL_LOG_LEVEL: DEBUG
    ports:
      - 8000:8000

volumes:
  postgres_data:
